---
abstract: 'Put each CPAN distribution into its own Github repo'
author:
  - 'Michael G. Schwern <schwern@pobox.com>'
build_requires:
  Test::Most: '0'
  Test::TypeConstraints: '0.05'
configure_requires:
  Module::Build: '0.42'
  Path::Tiny: '0.054'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.142060'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Gitpan
provides:
  Gitpan:
    file: lib/Gitpan.pm
    version: v2.3.0
  Gitpan::CPAN::Author:
    file: lib/Gitpan/CPAN/Author.pm
  Gitpan::CPAN::Authors:
    file: lib/Gitpan/CPAN/Authors.pm
  Gitpan::Config:
    file: lib/Gitpan/Config.pm
  Gitpan::ConfigFile:
    file: lib/Gitpan/ConfigFile.pm
  Gitpan::Dist:
    file: lib/Gitpan/Dist.pm
  Gitpan::Dummy:
    file: lib/Gitpan.pm
  Gitpan::Git:
    file: lib/Gitpan/Git.pm
  Gitpan::Github:
    file: lib/Gitpan/Github.pm
  Gitpan::OO:
    file: lib/Gitpan/OO.pm
  Gitpan::Release:
    file: lib/Gitpan/Release.pm
  Gitpan::Repo:
    file: lib/Gitpan/Repo.pm
  Gitpan::Role::CanBackoff:
    file: lib/Gitpan/Role/CanBackoff.pm
  Gitpan::Role::CanDistLog:
    file: lib/Gitpan/Role/CanDistLog.pm
  Gitpan::Role::CanLog:
    file: lib/Gitpan/Role/CanLog.pm
  Gitpan::Role::HasBackpanIndex:
    file: lib/Gitpan/Role/HasBackpanIndex.pm
  Gitpan::Role::HasCPANAuthors:
    file: lib/Gitpan/Role/HasCPANAuthors.pm
  Gitpan::Role::HasConfig:
    file: lib/Gitpan/Role/HasConfig.pm
  Gitpan::Role::HasUA:
    file: lib/Gitpan/Role/HasUA.pm
  Gitpan::Types:
    file: lib/Gitpan/Types.pm
  Gitpan::perl5i:
    file: lib/Gitpan/perl5i.pm
requires:
  Archive::Extract: '0.72'
  Archive::Zip: '1.39'
  BackPAN::Index: '0.39'
  Email::Valid: '1.195'
  Git::Raw: '0.49'
  Git::Repository: '1.3'
  Git::Repository::Log: '1.312'
  Git::Repository::Status: '0.03'
  Import::Into: '1.002000'
  Method::Signatures: '20141021'
  Moo: '1.006000'
  Parallel::ForkManager: '1.06'
  Path::Tiny: '0.059'
  Pithub: '0.01027'
  Type::Library: '0.046'
  Type::Utils: '0.046'
  Types::Standard: '0.046'
  YAML::XS: '0'
  perl: v5.18.1
  perl5i::2: v2.13.0
version: v2.3.0
